name: Lint and test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm ci

      - run: npm run lint:scripts
      - run: npm run generate
      - run: npm run lint
      - run: npm run typecheck
